<a href="https://colab.research.google.com/github/syahrulrez/Nurfira-Ramadhan-UTS-NLP/blob/main/20230420500043.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Ganjil.csv to Ganjil.csv

In [ ]:
import pandas as pd

# Ganti nama file sesuai file kamu
df = pd.read_csv('Ganjil.csv')

# Lihat data
df.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                   No;Berita
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...   KPK Bakal Siapkan SP3 :) !!!
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                                           NaN
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                                           NaN
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                                           NaN
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                                           NaN

1. Text Cleaning (Pembersihan Teks)

In [ ]:
import re

def clean_text(text):
    text = str(text)
    text = re.sub(r'http\S+', '', text)  # hapus URL
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # hapus angka & simbol
    text = re.sub(r'\s+', ' ', text).strip()  # hapus spasi berlebih
    return text

# Fix for the KeyError: 'Berita' due to incorrect CSV parsing
# If 'No;Berita' column exists, extract the 'Berita' part.
if 'No;Berita' in df.columns:
    # Use str.partition to safely get the part after the first semicolon
    # The partition method returns a DataFrame, so we access the third column directly by index [2]
    df['Berita_content'] = df['No;Berita'].astype(str).str.partition(';')[2]
    df['cleaning'] = df['Berita_content'].apply(clean_text)
    df[['Berita_content', 'cleaning']].head()
elif 'Berita' in df.columns:
    # If 'Berita' column already exists (e.g., if the CSV reading was fixed elsewhere),
    # proceed with the original logic.
    df['cleaning'] = df['Berita'].apply(clean_text)
    df[['Berita', 'cleaning']].head()
else:
    # Handle case where neither expected column is found (e.g., different column names)
    print("Error: Neither 'Berita' nor 'No;Berita' column found. Please check your DataFrame columns.")
    print("Available columns:", df.columns.tolist())

In [ ]:
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Pastikan sudah mendownload resource NLTK yang diperlukan
import nltk
nltk.download('punkt')
nltk.download('stopwords')

def clean_text(text):
    # 1. Mengubah teks menjadi lowercase (huruf kecil)
    text = text.lower()

    # 2. Menghapus URL (jika ada)
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # 3. Menghapus karakter spesial, angka, dan emoji
    # Kita hanya menyisakan huruf a-z
    text = re.sub(r'[^a-z\s]', '', text)

    # 4. Menghapus tanda baca (punctuation)
    text = text.translate(str.maketrans('', '', string.punctuation))

    # 5. Tokenisasi (memecah kalimat menjadi kata)
    tokens = word_tokenize(text)

    # 6. Menghapus Stopwords (kata umum yang kurang bermakna seperti 'yang', 'di', 'ke')
    stop_words = set(stopwords.words('indonesian'))
    # Opsional: Tambahkan kata spesifik yang ingin dibuang (misal: 'kompascom')
    additional_stop_words = {'kompascom', 'baca', 'juga'}
    stop_words.update(additional_stop_words)

    filtered_text = [word for word in tokens if word not in stop_words]

    # Menggabungkan kembali menjadi satu string
    return " ".join(filtered_text)

# Input Kalimat
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

cleaned_text = clean_text(raw_text)

print("--- Teks Sebelum Cleaning ---")
print(raw_text)
print("\n--- Teks Sesudah Cleaning ---")
print(cleaned_text)

--- Teks Sebelum Cleaning ---

JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!


--- Teks Sesudah Cleaning ---
jakarta komisi pemberantasan korupsi kpk nama pengusaha rokok khairul umam alias haji her tercantum dokumen ditemukan penyidik menggeledah kantor direktorat jenderal bea cukai djbc plt direktur penyidikan kpk achmad taufik husein termuat alasan kpk memanggil haji her saksi terkait dugaan korupsi lingkungan djbc haji her hasil penggeledahan temukan proses penyidikan kantor ditjen bea cukai dokumendokumen ocoy kasi intelijen djbc orlando hamonangan si tersangka taufik gedung merah putih jakarta senin analisisanalisis situlah ditemukan namanama pengusaha rokok suryo haji her sambung tersangka siman bahar meninggal dunia kpk siapkan sp

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

2. TOKENIZATION

In [ ]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab') # Add this line to download the missing resource

df['tokenizing'] = df['cleaning'].apply(word_tokenize)

df[['cleaning', 'tokenizing']].head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

                                                                                                                                                                                                                                                                                                                                                                                                                              cleaning  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN
                                                                                                                                                                                                                                                                                                                                                                           NaN

                                                                                                                                                                                                                                                                                                                                                                                                                              tokenizing
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...         []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                        []

In [ ]:
kalimat = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"
pisah = kalimat.split()
print(pisah)

['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']

3. NORMALIZATION

In [ ]:
# contoh kamus sederhana
normalisasi = {
    "gk": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "kpk": "komisi pemberantasan korupsi"
}

def normalize_text(tokens):
    return [normalisasi.get(word, word) for word in tokens]

df['normalization'] = df['tokenizing'].apply(normalize_text)

df[['tokenizing', 'normalization']].head()

                                                                                                                                                                                                                                                                                                                                                                                                                              tokenizing  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...         []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                        []

                                                                                                                                                                                                                                                                                                                                                                                                                              normalization
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...            []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                           []

In [ ]:
import re

def normalize_text(text):
    # Mapping normalisasi: "Kata Tidak Baku/Singkatan": "Kata Baku"
    normalization_dict = {
        "kpk": "komisi pemberantasan korupsi",
        "djbc": "direktorat jenderal bea cukai",
        "plt": "pelaksana tugas",
        "ditjen": "direktorat jenderal",
        "sp3": "surat perintah penghentian penyidikan",
        "kasi": "kepala seksi"
    }

    # 1. Kecilkan huruf terlebih dahulu agar match dengan dictionary
    text = text.lower()

    # 2. Tokenisasi sederhana untuk mencocokkan kata per kata
    words = text.split()

    # 3. Proses penggantian kata
    normalized_words = []
    for word in words:
        # Menghapus tanda baca yang menempel pada kata (misal: "djbc.")
        clean_word = word.strip(string.punctuation)

        if clean_word in normalization_dict:
            # Ganti dengan versi panjangnya
            replacement = normalization_dict[clean_word]
            normalized_words.append(replacement)
        else:
            normalized_words.append(word)

    return " ".join(normalized_words)

# Contoh penggunaan dengan teks yang sudah dibersihkan sedikit (atau teks asli)
raw_text = "Plt Direktur Penyidikan KPK mengatakan ada dokumen di kantor DJBC terkait tersangka."

normalized_result = normalize_text(raw_text)

print("--- Sebelum Normalisasi ---")
print(raw_text)
print("\n--- Sesudah Normalisasi ---")
print(normalized_result)

--- Sebelum Normalisasi ---
Plt Direktur Penyidikan KPK mengatakan ada dokumen di kantor DJBC terkait tersangka.

--- Sesudah Normalisasi ---
pelaksana tugas direktur penyidikan komisi pemberantasan korupsi mengatakan ada dokumen di kantor direktorat jenderal bea cukai terkait tersangka.

4. Stopword Removal

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('indonesian'))

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

df['stopword'] = df['normalization'].apply(remove_stopwords)

df[['normalization', 'stopword']].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                                                                                                                                                                                                                                                                                                                                                                                                              normalization  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...            []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                           []

                                                                                                                                                                                                                                                                                                                                                                                                                              stopword
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...       []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                      []

In [ ]:
!pip install Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
import re

# 1. Inisialisasi Factory Stopword Sastrawi
factory = StopWordRemoverFactory()
stopword_remover = factory.create_stop_word_remover()

# 2. Teks asli
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

# 3. Pre-processing sederhana (Lowercasing)
# Stopword removal bekerja lebih baik jika teks sudah dalam huruf kecil
clean_text = raw_text.lower()

# 4. Proses Penghapusan Stopwords
result = stopword_remover.remove(clean_text)

print("--- Teks Setelah Stopword Removal ---")
print(result)

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 6.3 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1
--- Teks Setelah Stopword Removal ---

jakarta, kompas.com - komisi pemberantasan korupsi (kpk) mengatakan, nama pengusaha rokok khairul umam alias haji her tercantum dokumen ditemukan penyidik menggeledah kantor direktorat jenderal bea cukai (djbc). plt direktur penyidikan kpk achmad taufik husein mengatakan, termuat tersebut menjadi alasan kpk memanggil haji her saksi terkait kasus dugaan korupsi lingkungan djbc. “haji her, kembali, jadi hasil penggeledahan temukan proses penyidikan kantor ditjen bea cukai ada beberapa dokumen-dokumen dibuat ocoy (kasi intelijen djbc orlando hamonangan) si tersangka ini,” kata taufik, gedung merah putih, jakarta, senin (13/4/2026). “kemudian kita analisis-analisis. situlah ditemukan beberapa nama-nama pengusaha rokok. suryo termasuk haji her,” sambung dia. baca juga: tersangka siman bahar meninggal dunia, kpk bakal siapkan sp3 :) !!!

5. Case Folding

In [ ]:
def case_folding(tokens):
    return [word.lower() for word in tokens]

df['casefolding'] = df['stopword'].apply(case_folding)

df[['stopword', 'casefolding']].head()

                                                                                                                                                                                                                                                                                                                                                                                                                              stopword  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...       []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                      []

                                                                                                                                                                                                                                                                                                                                                                                                                              casefolding
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...          []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                         []

In [ ]:
#import word_tokenize dari modul nltk
from nltk.tokenize import word_tokenize

kalimat = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"

tokens = nltk.tokenize.word_tokenize(kalimat)
print(tokens)

['JAKARTA', ',', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(', 'KPK', ')', 'mengatakan', ',', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(', 'DJBC', ')', '.', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan', ',', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC', '.', '“', 'Haji', 'Her', ',', 'saya', 'kembali', ',', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(', 'Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan', ')', 'si', 'tersangka', 'ini', ',', '”', 'kata', 'Taufik', ',', 'di', 'Gedung', 'Merah', 'Putih', ',', 'Jakarta', ',', 'Senin', '(', '13/4/2026', ')', '.', '“', 'Kemudian', 'kita', 'analisis-analisis', '.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok', '.', 'Suryo', 'termasuk', 'Haji', 'Her', ',', '”', 'sambung', 'dia', '.', 'Baca', 'juga', ':', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia', ',', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':', ')', '!', '!', '!']

In [ ]:
from nltk.tokenize import word_tokenize
import string

kalimat = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"

kalimat = kalimat.translate(str.maketrans('', '', string.punctuation)).lower()
__builtins__.print(kalimat)

jakarta kompascom  komisi pemberantasan korupsi kpk mengatakan nama pengusaha rokok khairul umam alias haji her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor direktorat jenderal bea cukai djbc plt direktur penyidikan kpk achmad taufik husein mengatakan termuat tersebut menjadi alasan kpk memanggil haji her sebagai saksi terkait kasus dugaan korupsi di lingkungan djbc “haji her saya kembali jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor ditjen bea cukai itu ada beberapa dokumendokumen yang dibuat oleh ocoy kasi intelijen djbc orlando hamonangan si tersangka ini” kata taufik di gedung merah putih jakarta senin 1342026 “kemudian kita analisisanalisis di situlah ditemukan beberapa namanama pengusaha rokok suryo termasuk haji her” sambung dia baca juga tersangka siman bahar meninggal dunia kpk bakal siapkan sp3

In [ ]:
# Teks asli
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

def case_folding(text):
    # Menggunakan fungsi bawaan Python .lower()
    return text.lower()

# Eksekusi
folded_text = case_folding(raw_text)

print("--- Hasil Case Folding ---")
print(folded_text)

--- Hasil Case Folding ---

jakarta, kompas.com - komisi pemberantasan korupsi (kpk) mengatakan, nama pengusaha rokok khairul umam alias haji her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor direktorat jenderal bea cukai (djbc). plt direktur penyidikan kpk achmad taufik husein mengatakan, termuat tersebut menjadi alasan kpk memanggil haji her sebagai saksi terkait kasus dugaan korupsi di lingkungan djbc. “haji her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor ditjen bea cukai itu ada beberapa dokumen-dokumen yang dibuat oleh ocoy (kasi intelijen djbc orlando hamonangan) si tersangka ini,” kata taufik, di gedung merah putih, jakarta, senin (13/4/2026). “kemudian kita analisis-analisis. di situlah ditemukan beberapa nama-nama pengusaha rokok. suryo termasuk haji her,” sambung dia. baca juga: tersangka siman bahar meninggal dunia, kpk bakal siapkan sp3 :) !!!

6. Stemming

In [ ]:
!pip install Sastrawi

Requirement already satisfied: Sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)

In [ ]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(tokens):
    return [stemmer.stem(word) for word in tokens]

df['stemming'] = df['casefolding'].apply(stemming)

df[['casefolding', 'stemming']].head()

                                                                                                                                                                                                                                                                                                                                                                                                                              casefolding  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...          []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                         []

                                                                                                                                                                                                                                                                                                                                                                                                                              stemming
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...       []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                      []

In [ ]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# 1. Inisialisasi Stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# 2. Teks asli
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

# 3. Proses Stemming
# Stemmer Sastrawi secara otomatis melakukan lowercase sebelum memproses
stemmed_text = stemmer.stem(raw_text)

print("--- Hasil Stemming ---")
print(stemmed_text)

--- Hasil Stemming ---
jakarta kompas com - komisi berantas korupsi kpk kata nama usaha rokok khairul umam alias haji her ada cantum dalam dokumen yang temu sidik saat geledah kantor direktorat jenderal bea cukai djbc plt direktur sidi kpk achmad taufik husein kata muat sebut jadi alas kpk panggil haji her bagai saksi kait kasus duga korupsi di lingkung djbc haji her saya kembali jadi hasil geledah yang kita temu di proses sidi di kantor ditjen bea cukai itu ada beberapa dokumen yang buat oleh ocoy kasi intelijen djbc orlando hamonangan si sangka ini kata taufik di gedung merah putih jakarta senin 13 4 2026 kemudian kita analisis di situ temu beberapa nama usaha rokok suryo masuk haji her sambung dia baca juga sangka siman bahar tinggal dunia kpk bakal siap sp3

In [ ]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

kata = ["JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"]

for k in kata:
    print(k, ":", ps.stem(k))

JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!! : jakarta, kompas.com - komisi pemberantasan korupsi (kpk) mengatakan, nama pengusaha rokok khairul umam alias haji her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor direktorat jenderal bea cukai (djbc). plt direktur penyidikan kpk achmad taufik husein mengatakan, termuat tersebut menjadi alasan kpk memanggil haji her sebagai saksi terkait kasus dugaan korupsi di lingkungan djbc. “haji her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor ditjen bea cukai itu ada beberapa dokumen-dokumen yang dibuat oleh ocoy (kasi intelijen djbc orlando hamonangan) si tersangka ini,” kata taufik, di gedung merah putih, jakarta, senin (13/4/2026). “kemudian kita analisis-analisis. di situlah ditemukan beberapa nama-nama pengusaha rokok. suryo termasuk haji her,” sambung dia. baca juga: tersangka siman bahar meninggal dunia, kpk bakal siapkan sp3 :) !!!

In [ ]:
from nltk.stem import PorterStemmer

porter_stemmer = PorterStemmer()

words = ["JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"]

stemmed_words = [porter_stemmer.stem(word) for word in words]

print("Original words:", words)

print("Stemmed words:", stemmed_words)

Original words: ['JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!']
Stemmed words: ['jakarta, kompas.com - komisi pemberantasan korupsi (kpk) mengatakan, nama pengusaha rokok khairul umam alias haji her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor direktorat jenderal bea cukai (djbc). plt direktur penyidikan kpk achmad taufik husein mengatakan, termuat tersebut menjadi alasan kpk memanggil haji her sebagai saksi terkait kasus dugaan korupsi di lingkungan djbc. “haji her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor ditjen bea cukai itu ada beberapa dokumen-dokumen yang dibuat oleh ocoy (kasi intelijen djbc orlando hamonangan) si tersangka ini,” kata taufik, di gedung merah putih, jakarta, senin (13/4/2026). “kemudian kita analisis-analisis. di situlah ditemukan beberapa nama-nama pengusaha rokok. suryo termasuk haji her,” sambung dia. baca juga: tersangka siman bahar meninggal dunia, kpk bakal siapkan sp3 :) !!!']

In [ ]:
from nltk.stem import SnowballStemmer

stemmer = SnowballStemmer (language='english')

words_to_stem = ['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']

stemmed_words = [stemmer.stem(word) for word in words_to_stem]

print("Original words:", words_to_stem)

print("Stemmed words:", stemmed_words)

Original words: ['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']
Stemmed words: ['jakarta,', 'kompas.com', '-', 'komisi', 'pemberantasan', 'korupsi', '(kpk)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'khairul', 'umam', 'alia', 'haji', 'her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'direktorat', 'jender', 'bea', 'cukai', '(djbc).', 'plt', 'direktur', 'penyidikan', 'kpk', 'achmad', 'taufik', 'husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'kpk', 'memanggil', 'haji', 'her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'djbc.', '“haji', 'her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'prose', 'penyidikan', 'di', 'kantor', 'ditjen', 'bea', 'cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'ocoy', '(kasi', 'intelijen', 'djbc', 'orlando', 'hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'taufik,', 'di', 'gedung', 'merah', 'putih,', 'jakarta,', 'senin', '(13/4/2026).', '“kemudian', 'kita', 'analisis-analisis.', 'di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'suryo', 'termasuk', 'haji', 'her,”', 'sambung', 'dia.', 'baca', 'juga:', 'tersangka', 'siman', 'bahar', 'meningg', 'dunia,', 'kpk', 'bakal', 'siapkan', 'sp3', ':)', '!!!']

In [ ]:
from nltk.stem import LancasterStemmer

stemmer = LancasterStemmer()

words_to_stem = ['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']

stemmed_words = [stemmer.stem(word) for word in words_to_stem]

print("Original words:", words_to_stem)

print("Stemmed words:", stemmed_words)

Original words: ['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']
Stemmed words: ['jakarta,', 'kompas.com', '-', 'komis', 'pemberantas', 'korups', '(kpk)', 'mengatakan,', 'nam', 'pengusah', 'rokok', 'khair', 'umam', 'alia', 'haj', 'her', 'ad', 'tercant', 'dalam', 'dokum', 'yang', 'ditemuk', 'penyidik', 'saat', 'menggeledah', 'kant', 'direkt', 'jend', 'bea', 'cuka', '(djbc).', 'plt', 'direkt', 'penyidik', 'kpk', 'achmad', 'taufik', 'husein', 'mengatakan,', 'termu', 'tersebut', 'menjad', 'alas', 'kpk', 'memanggil', 'haj', 'her', 'sebaga', 'saks', 'terkait', 'kas', 'duga', 'korups', 'di', 'lingkung', 'djbc.', '“haji', 'her,', 'say', 'kembali,', 'jad', 'hasil', 'penggeledah', 'yang', 'kit', 'temuk', 'di', 'pros', 'penyidik', 'di', 'kant', 'dits', 'bea', 'cuka', 'itu', 'ad', 'beberap', 'dokumen-dokum', 'yang', 'dibu', 'oleh', 'ocoy', '(kasi', 'intelid', 'djbc', 'orlando', 'hamonangan)', 'si', 'tersangk', 'ini,”', 'kat', 'taufik,', 'di', 'gedung', 'merah', 'putih,', 'jakarta,', 'senin', '(13/4/2026).', '“kemudian', 'kit', 'analisis-analisis.', 'di', 'situlah', 'ditemuk', 'beberap', 'nama-nam', 'pengusah', 'rokok.', 'suryo', 'termasuk', 'haj', 'her,”', 'sambung', 'dia.', 'bac', 'juga:', 'tersangk', 'sim', 'bah', 'mening', 'dunia,', 'kpk', 'bak', 'siapk', 'sp3', ':)', '!!!']

7. Lemmatization

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

def lemmatization(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

df['lemmatization'] = df['stemming'].apply(lemmatization)

df[['stemming', 'lemmatization']].head()

[nltk_data] Downloading package wordnet to /root/nltk_data...

                                                                                                                                                                                                                                                                                                                                                                                                                              stemming  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...       []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                      []

                                                                                                                                                                                                                                                                                                                                                                                                                              lemmatization
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...            []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                           []

In [ ]:
from nltk.tokenize import word_tokenize

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
text = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"
tokens = word_tokenize(text)

lemmatized_words = [lemmatizer.lemmatize(word) for word in tokens]

print(f"Original Text: {text}")

print(f"Lemmatized Words: {lemmatized_words}")

Original Text: JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
Lemmatized Words: ['JAKARTA', ',', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(', 'KPK', ')', 'mengatakan', ',', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(', 'DJBC', ')', '.', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan', ',', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC', '.', '“', 'Haji', 'Her', ',', 'saya', 'kembali', ',', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'prose', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(', 'Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan', ')', 'si', 'tersangka', 'ini', ',', '”', 'kata', 'Taufik', ',', 'di', 'Gedung', 'Merah', 'Putih', ',', 'Jakarta', ',', 'Senin', '(', '13/4/2026', ')', '.', '“', 'Kemudian', 'kita', 'analisis-analisis', '.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok', '.', 'Suryo', 'termasuk', 'Haji', 'Her', ',', '”', 'sambung', 'dia', '.', 'Baca', 'juga', ':', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia', ',', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':', ')', '!', '!', '!']

In [ ]:
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet # Import wordnet for POS tags
import nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

lemmatizer = WordNetLemmatizer()
sentence = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"
tokens = word_tokenize(sentence)
tagged_tokens = pos_tag(tokens)

def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return 'a'
    elif tag.startswith('V'):
        return 'v'
    elif tag.startswith('N'):
        return 'n'
    elif tag.startswith('R'):
        return 'r'
    else:
        return 'n'

lemmatized_sentence = []
for word, tag in tagged_tokens:
    lemmatized_sentence.append(lemmatizer.lemmatize(word, get_wordnet_pos(tag)))

print(f"Original Sentence: {sentence}")
print(f"Lemmatized Sentence: {' '.join(lemmatized_sentence)}")

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

Original Sentence: JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
Lemmatized Sentence: JAKARTA , KOMPAS.com - Komisi Pemberantasan Korupsi ( KPK ) mengatakan , nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai ( DJBC ) . Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan , termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC . “ Haji Her , saya kembali , jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy ( Kasi Intelijen DJBC Orlando Hamonangan ) si tersangka ini , ” kata Taufik , di Gedung Merah Putih , Jakarta , Senin ( 13/4/2026 ) . “ Kemudian kita analisis-analisis . Di situlah ditemukan beberapa nama-nama pengusaha rokok . Suryo termasuk Haji Her , ” sambung dia . Baca juga : Tersangka Siman Bahar Meninggal Dunia , KPK Bakal Siapkan SP3 : ) ! ! !

In [ ]:
!pip install stanza
import stanza

# 1. Download dan inisialisasi model bahasa Indonesia
stanza.download('id') # Jalankan ini jika pertama kali menggunakan
nlp = stanza.Pipeline('id', processors='tokenize,lemma')

# 2. Teks asli
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

# 3. Proses Lemmatization
doc = nlp(raw_text)

# 4. Mengambil lemma dari setiap kata
lemmatized_words = [word.lemma for sent in doc.sentences for word in sent.words]

# Menggabungkan kembali menjadi string
lemmatized_text = " ".join(lemmatized_words)

print("--- Hasil Lemmatization (Stanza) ---")
print(lemmatized_text)

Collecting stanza
  Downloading stanza-1.11.1-py3-none-any.whl.metadata (14 kB)
Collecting emoji (from stanza)
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from stanza) (2.0.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from stanza) (4.9.4)
Requirement already satisfied: protobuf>=3.15.0 in /usr/local/lib/python3.12/dist-packages (from stanza) (5.29.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from stanza) (2.32.4)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from stanza) (3.6.1)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from stanza) (2.10.0+cpu)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from stanza) (4.67.3)
Collecting udtools>=0.2.4 (from stanza)
  Downloading udtools-0.2.7-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (2025.3.0)
Collecting udapi>=0.5.0 (from udtools>=0.2.4->stanza)
  Downloading udapi-0.5.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: regex>=2020.09.27 in /usr/local/lib/python3.12/dist-packages (from udtools>=0.2.4->stanza) (2025.11.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->stanza) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->stanza) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->stanza) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->stanza) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->stanza) (1.3.0)
Collecting colorama (from udapi>=0.5.0->udtools>=0.2.4->stanza)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: termcolor in /usr/local/lib/python3.12/dist-packages (from udapi>=0.5.0->udtools>=0.2.4->stanza) (3.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->stanza) (3.0.3)
Downloading stanza-1.11.1-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 29.2 MB/s eta 0:00:00
Downloading udtools-0.2.7-py3-none-any.whl (773 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 773.7/773.7 kB 25.8 MB/s eta 0:00:00
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 26.2 MB/s eta 0:00:00
Downloading udapi-0.5.2-py3-none-any.whl (418 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 418.7/418.7 kB 20.2 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: emoji, colorama, udapi, udtools, stanza
Successfully installed colorama-0.4.6 emoji-2.15.0 stanza-1.11.1 udapi-0.5.2 udtools-0.2.7

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.11.0/resources/resources.json
INFO:stanza:Downloading default packages for language: id (Indonesian) ...

Downloading https://huggingface.co/stanfordnlp/stanza-id/resolve/v1.11.0/models/default.zip:   0%|          | …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.11.0/resources/id/default.zip
INFO:stanza:Finished downloading models and saved to /root/.cache/stanza/1.11.0/resources
INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.11.0/resources/resources.json
WARNING:stanza:Language id package default expects mwt, which has been added
INFO:stanza:Loading these models for language: id (Indonesian):
============================
| Processor | Package      |
----------------------------
| tokenize  | gsd          |
| mwt       | gsd          |
| lemma     | gsd_nocharlm |
============================

INFO:stanza:Using device: cpu
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: lemma
INFO:stanza:Done loading processors!

--- Hasil Lemmatization (Stanza) ---
jakarta , kompas.com - komisi penberantasan korupsi ( kpk ) kata , nama usaha rokok khairul umam alias haji her ada cantum dalam dokumen yang temu sidik saat geledah kantor direktorat jenderal bea cukai ( djbc ) . plt direktur sidi kpk achmad taufik husein kata , muat tersebut jadi alasan kpk panggil haji her sebagai saksi kait kasus duga korupsi di lingkung djbc . “ haji her , saya kembali , jadi hasil geledah yang kita temu di proses sidik di kantor ditjen bea cukai itu ada beberapa dokumen yang buat oleh ocoy ( kasi intelijen djbc orlando hamonangan ) si sangka ini , ” kata taufik , di gedung merah putih , jakarta , senin ( 13/4 / 2026 ) . “ kemudian kita analisis . di situ lah temu beberapa nama usaha rokok . suryo termasuk haji her , ” sambung dia . baca juga : tangka siman bahar tinggal dunia , kpk bakal siap sp3 : ) ! ! !